### ISSUE TITLE
Never reads AD5 port

### ISSUE THREAD

**Issue by stubby-phillips** [borisboc/RaspberryPi-ADC-DAC#2]
In ADS1256_RemapChannelIndex() you are missing
...
case 4:
		return 5;
...

**Comment by AKEOPLUS-boris-bocquet** [comment]
How yeah sure my bad. Since I am not using all the channels in my projects, I never remarked it. Commit 808ae032b0988ec7a8d08c7a328a3b3a60c3ba69 solved this issue. I let you check and close.
Kind regards.
Boris

**Comment by stubby-phillips** [comment]
Thanks...
